### ISSUE TITLE
Other tags?

### ISSUE THREAD

**Issue by drazisil** [rust-osdev/multiboot2#69]
I see that both `get_tag` and `tags` are not public, is there any reason for this? I'd love to be able to query what other tags may be in the header.

**Comment by robert-w-gries** [comment]
[This is the only discussion I could find regarding the visibility of tags](https://github.com/rust-osdev/multiboot2-elf64/pull/9#issuecomment-247405184)

@phil-opp any updates regarding this?

**Comment by phil-opp** [comment]
I left that comment over 4 years ago :D. So I don't really remember why I was against new public items back then. I guess that I just wanted to be careful about safety, since e.g. the tag iterator type performs unsafe operations internally.

On a quick look, I think exporting the `Tag` type and `get_tag` function should be fine. The `TagIter` type in its current form seems unsafe so we shouldn't expose it, but I think we can export the `tags()` function after changing its return type to `impl Iterator<Item = &Tag>`.

**Comment by robert-w-gries** [comment]
Thanks @phil-opp! It's hard to believe it's been so long since the rust OS projects started

@drazisil feel free to submit a PR. If needed, I can probably work on it this weekend

**Comment by phil-opp** [comment]
Yeah, for me too!

**Comment by drazisil** [comment]
@robert-w-gries I will try to find time to work on this. Someone else can tackle it first if they have time, I won't be offended :)

**Comment by phip1611** [comment]
Probably we can close this, because we also closed #75  

What do u think @IsaacWoods ?

**Comment by drazisil** [comment]
Well, I completely forgot about it  I have no problem with closing it.
