### ISSUE TITLE
Changelog is outdated

### ISSUE THREAD

**Issue by phip1611** [rust-osdev/multiboot2#78]
Changelog.md hasn't been modified for 13 months now.. Maybe one should fix this?

**Comment by IsaacWoods** [comment]
Yes - this basically happened when Phil handed over the maintainership of this crate to the @rust-osdev/multiboot2 team. I think I've released all of the versions since then, and tbh I forgot this crate has a changelog, and so have not been updating it. My bandwidth is fairly limited these days due to my degree, and I no longer actually use this library, so it only gets my attention when I get a notification tbh.

That being said, movement is slow enough that I don't feel a changelog is particularly necessary - people can read through the PRs if they choose, and I try and announce large changes on our monthly newsletter, which I feel provides a more accessible image of the ecosystem's development.

Please feel free to send a PR if you'd like to see the changelog updated, and I'd happily accept it. If you'd like to be more involved in the library's development, I'd be more than happy to add you to the team, but we'd need Phil to add you to the organisation first - let me know.

**Comment by phip1611** [comment]
> Please feel free to send a PR if you'd like to see the changelog updated
I agree that it is not that important. I'll see if I have some time in the next days.

> If you'd like to be more involved in the library's development, I'd be more than happy to add you to the team, but we'd need Phil to add you to the organisation first - let me know.

I absolutely would appreciate this. I love the Rust world and would highly appreciate it to improve the OS-Dev ecosystem. @IsaacWoods

**Comment by IsaacWoods** [comment]
> I absolutely would appreciate this. I love the Rust world and would highly appreciate it to improve the crates living in the OS-Dev space

Great :)

@phil-opp could you invite @phip1611 to the organisation please? I can then add him to the multiboot team.

**Comment by phil-opp** [comment]
Sure, invite sent! Welcome @phip1611, and thanks a lot your help!
